spring:
  datasource:
    url: jdbc:h2:mem:dojoMock
    driverClassName: org.h2.Driver
    username: admin
    password: adminBD@321
    database-plataform: org.hibernate.dialect.H2Dialect
server:
  port: ${PORT:8080}
  servlet:
    contextPath: /transacoes-api
